[package]
name = "fishnet"
version = "2.6.4-irwin-dev"
description = "Distributed Stockfish analysis for lichess.org"
repository = "https://github.com/lichess-org/fishnet"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["command-line-utilities", "web-programming::http-client", "games"]
keywords = ["chess", "lichess"]
edition = "2021"
exclude = [
    "Stockfish/**/*.o",
    "Stockfish/**/*.s",
    "Stockfish/**/.depend",
    "Stockfish/**/*.nnue",
    "MultiVariant-Stockfish/**/*.o",
    "MultiVariant-Stockfish/**/*.s",
    "MultiVariant-Stockfish/**/.depend",
    "MultiVariant-Stockfish/**/*.nnue",
]

[profile.release]
strip = false

[dependencies]
arrayvec = "0.7"
atty = "0.2"
bitflags = "1"
clap = { version = "3", features = ["derive", "deprecated"] }
configparser = "3"
xz2 = "0.1"
rand = "0.8"
reqwest = { version = "0.11", features = ["json", "rustls-tls-manual-roots"], default-features = false }
rustls = "0.20" # will fail at runtime if mismatch with reqwest
self_update = { version = "0.30", features = ["rustls"], default-features = false }
serde = "1"
serde_json = "1"
serde_with = "2"
home = "0.5"
shakmaty = { version = "0.21", features = ["variant"] }
shell-escape = "0.1"
tempfile = "3"
tokio = { version = "1", features = ["rt", "macros", "sync", "time", "signal", "process", "io-util"], default-features = false }
url = "2"
serde_repr = "0.1"
webpki-roots = "0.22"
thousands = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "10"

[build-dependencies]
glob = "0.3"
xz2 = "0.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
